name: Playwright Tests
on:
  push:
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
    - name: build
      run: npm run build
    - name: install xvfb
      run: "! which xvfb-run > /dev/null && sudo apt update && sudo apt install -y xvfb || true"
      if: matrix.os == 'ubuntu-latest'
    - name: Run Playwright tests with xvfb
      run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test:e2e
      if: matrix.os == 'ubuntu-latest'
    - name: Run Playwright tests
      run: npm run test:e2e
      if: matrix.os != 'ubuntu-latest'
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
